stages:
  data_ingestion:
    cmd: python src/data/load_data.py
    deps:
      - data/input/
      - src/data/load_data.py
    outs:
      - data/raw/:
          persist: true

  data_preprocessing:
    cmd: python src/data/preprocess.py
    deps:
      - data/raw/
      - src/data/preprocess.py
    outs:
      - data/processed/:
          persist: true

  feature_engineering:
    cmd: python src/features/engineer_features.py
    deps:
      - data/processed/
      - src/features/engineer_features.py
    outs:
      - data/features/:
          persist: true

  model_training:
    cmd: python src/models/train_model.py
    deps:
      - data/features/
      - src/models/train_model.py
    outs:
      - models/:
          persist: true

  model_evaluation:
    cmd: python src/models/evaluate_model.py
    deps:
      - data/features/
      - models/
      - src/models/evaluate_model.py
    outs:
      - reports/:
          persist: true 